<Project Sdk="Microsoft.NET.Sdk">
    
    <PropertyGroup>
        <!-- Только здесь! -->
        <PackageId>MoneyToWordsFSharpLib</PackageId>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>
    
    <ItemGroup>
        <!-- Domain -->
        <Compile Include="Domain\MoneyError.fs" />
        <Compile Include="Domain\Money.fs" />
        <Compile Include="Domain\Form.fs" />

        <!-- Application -->
        <Compile Include="Application\Declension.fs" />
        <Compile Include="Application\NumberToWords.fs" />

        <!-- Infrastructure -->
        <Compile Include="Infrastructure\RussianRules.fs" />
        <Compile Include="Infrastructure\TextOutput.fs" />

        <!-- Presentation -->
        <Compile Include="Presentation\MoneyErrors.fs" />
        <Compile Include="Presentation\MoneyToWords.fs" />
    </ItemGroup>

</Project>
