name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Features'
    labels: [ 'type:feature', 'feat' ]
  - title: '🐛 Bug Fixes'
    labels: [ 'type:bug', 'fix' ]
  - title: '🔧 Improvements'
    labels: [ improvement, optimize ]
  - title: '🧹 Refactoring'
    labels: [ 'type:refactor', 'code-quality' ]
  - title: '📚 Documentation'
    labels: [ 'type:docs', documentation ]
  - title: '⚙️ Maintenance'
    labels: [ 'type:chore', dependencies, 'dependency-update' ]
  - title: '💥 Breaking Changes'
    labels: [ major, breaking, 'backwards-incompatible' ]

exclude-labels:
  - ignore-for-release
  - skip-changelog
  - draft

version-resolver:
  major: { labels: [ major, breaking, 'backwards-incompatible' ] }
  minor: { labels: [ 'type:feature', feat, enhancement ] }
  patch: { labels: [ 'type:bug', fix, 'type:docs', docs, 'type:chore', 'type:refactor', ci ] }
  default: patch

change-template: '- $TITLE (#$NUMBER)'
template: |
  ## What's Changed

  $CHANGES

  ---
  ## How to Install
  ```bash
  dotnet add package MoneyToWordsFSharpLib --version $RESOLVED_VERSION
  ```

  Changelog
  Full changelog: [Compare $PREVIOUS_TAG...$NEXT_TAG](https://github.com/DivinMA/MoneyToWords/compare/$PREVIOUS_TAG...$NEXT_TAG)
