name: ❓ Задать вопрос
description: Не понимаете, как что-то работает?
title: "Question: "
labels: type:question, priority:low
assignees: DivinMA
body:
  - type: markdown
    attributes:
      value: |
        Задайте свой вопрос — постараемся помочь!

        🔍 Перед тем, как задать:
        - Проверьте [README.md](https://github.com/DivinMA/MoneyToWords/blob/main/README.md)
        - Изучите [CONTRIBUTING.md](https://github.com/DivinMA/MoneyToWords/blob/main/CONTRIBUTING.md)

  - type: textarea
    attributes:
      label: Вопрос
    validations:
      required: true

  - type: textarea
    attributes:
      label: Что вы уже попробовали?
