<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
        <RestorePackagesWithLockFile>false</RestorePackagesWithLockFile>
    </PropertyGroup>

    <Target Name="LogFallbackFolder" BeforeTargets="Restore">
        <Message Text="📁 DisableImplicitNuGetFallbackFolder = $(DisableImplicitNuGetFallbackFolder)" Importance="high" />
    </Target>

    <ItemGroup>
        <Compile Include="Program.fs" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\MoneyToWords\MoneyToWords.fsproj" />
    </ItemGroup>

</Project>
