name: Release Drafter

on:
  # Запускать при:
  pull_request:
    types:
      - opened      # когда PR создан
      - reopened    # когда PR восстановлен
      - synchronize # когда добавлены новые коммиты (push в ветку)
  pull_request_target:
    types:
      - closed      # когда PR замержен — обновить черновик

permissions:
  contents: write
  pull-requests: read

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release Draft
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}